name: Upload images

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload:
    name: Upload images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-deps

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://github.com/GoogleContainerTools/skaffold/releases/download/v2.14.2/skaffold-linux-amd64 --fail
          sudo install skaffold /usr/local/bin/
          skaffold version

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
          skopeo --version

      - id: auth
        name: Authenticate with GCP
        uses: google-github-actions/auth@3a3c4c57d294ef65efaaee4ff17b22fa88dd3c69 # v1.3.0
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_PUSH_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: turbopuffer-github-actions
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          registry: turbopuffer.azurecr.io

      - name: Release
        run: make az-release-ci
